name: Get New Image

on:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@vs
        with:
          node-version: 'latest'

      - name: Get New Image
        run: node image_get.js


      - name: Commit New Image
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "updating image"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
